spring:
  sql:
    init:
      platform: mariadb
      encoding: UTF-8
      mode: always

  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  #JPA
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
server:
  port: 8081