spring:
  sql:
    init:
      platform: mariadb
      encoding: UTF-8
      mode: always
  # private yml import
  profiles:
    include: private
#JPA
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: false
    show-sql: true
server:
  port: 8081


