spring:
  sql:
    init:
      platform: mariadb
      encoding: UTF-8
      mode: always
server:
  port: 8081

#JPA
jpa:
  hibernate:
    ddl-auto: create
  generate-ddl: false
  show-sql: true
# private yml import
profiles:
  include: private