name: bps
services:
#  proxy:
#    image: nginx
#    volumes:
#      - ./nginx/conf:/etc/nginx/conf.d
#    ports:
#      - "8888:80"
#    environment:
#      - NGINX_HOST=localhost
#      - NGINX_PORT=80
#    depends_on:
#      - bpsapp
  bpsapp:
    build: .
    ports:
      - 8081:8081 #outport/dockerport 
    environment:
      DB_URL: $DB_URL
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
    platform: linux/amd64